-- Curator console phase two: append-only audit records for administrator actions.
-- Run once in the Supabase SQL Editor before deploying the updated Edge Function.

begin;

create table if not exists public.admin_operation_logs (
  id bigint generated by default as identity primary key,
  actor_code_hash text not null check (char_length(actor_code_hash) = 64),
  actor_name text not null check (char_length(trim(actor_name)) between 1 and 40),
  actor_role text not null check (actor_role in ('admin', 'god', 'reviewer')),
  action text not null check (char_length(trim(action)) between 1 and 80),
  target_code_hash text check (target_code_hash is null or char_length(target_code_hash) = 64),
  target_name text not null default '' check (char_length(trim(target_name)) <= 40),
  object_type text not null default '' check (char_length(trim(object_type)) <= 40),
  object_id text not null default '' check (char_length(trim(object_id)) <= 120),
  summary text not null default '' check (char_length(trim(summary)) <= 500),
  before_state jsonb not null default '{}'::jsonb,
  after_state jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_operation_logs_created_idx
  on public.admin_operation_logs(created_at desc);
create index if not exists admin_operation_logs_target_idx
  on public.admin_operation_logs(target_code_hash, created_at desc)
  where target_code_hash is not null;
create index if not exists admin_operation_logs_actor_idx
  on public.admin_operation_logs(actor_code_hash, created_at desc);

alter table public.admin_operation_logs enable row level security;

grant usage on schema public to service_role;
grant select, insert on public.admin_operation_logs to service_role;

commit;

-- Verification: the result should contain the table definition.
select column_name, data_type
from information_schema.columns
where table_schema = 'public'
  and table_name = 'admin_operation_logs'
order by ordinal_position;
