-- Trial matching queue and room system.
-- Run after dungeon_setup.sql / per_person_invites_migration.sql.

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.match_rooms (
  id uuid primary key default gen_random_uuid(),
  dungeon_id uuid not null references public.dungeons(id) on delete cascade,
  target_player_count integer not null default 6 check (target_player_count >= 1 and target_player_count <= 99),
  room_status text not null default 'running' check (room_status in ('running', 'finished', 'cancelled')),
  created_at timestamptz not null default now(),
  finished_at timestamptz
);

create table if not exists public.match_queue (
  id bigint generated by default as identity primary key,
  dungeon_id uuid not null references public.dungeons(id) on delete cascade,
  player_code_hash text not null check (char_length(player_code_hash) = 64),
  player_name text not null check (char_length(trim(player_name)) between 1 and 40),
  status text not null default 'queued' check (status in ('queued', 'matched', 'cancelled')),
  room_id uuid references public.match_rooms(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.match_room_players (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.match_rooms(id) on delete cascade,
  dungeon_id uuid not null references public.dungeons(id) on delete cascade,
  player_code_hash text not null check (char_length(player_code_hash) = 64),
  player_name text not null check (char_length(trim(player_name)) between 1 and 40),
  finish_status boolean not null default false,
  joined_at timestamptz not null default now()
);

create unique index if not exists match_queue_one_active_player_idx
  on public.match_queue(dungeon_id, player_code_hash)
  where status = 'queued';

create unique index if not exists match_room_players_one_per_room_idx
  on public.match_room_players(room_id, player_code_hash);

create index if not exists match_queue_dungeon_status_idx
  on public.match_queue(dungeon_id, status, created_at, id);

create index if not exists match_rooms_dungeon_status_idx
  on public.match_rooms(dungeon_id, room_status, created_at desc);

create index if not exists match_room_players_player_idx
  on public.match_room_players(player_code_hash, joined_at desc);

create or replace function public.join_match_queue(
  p_dungeon_id uuid,
  p_player_code_hash text,
  p_player_name text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  target_count integer;
  queued_count integer;
  existing_room_id uuid;
  created_room_id uuid;
  clean_player_name text;
begin
  if p_dungeon_id is null then
    raise exception '副本 ID 不正确';
  end if;

  if p_player_code_hash is null or char_length(p_player_code_hash) <> 64 then
    raise exception '玩家身份不正确';
  end if;

  clean_player_name := nullif(trim(p_player_name), '');
  if clean_player_name is null then
    raise exception '玩家昵称不能为空';
  end if;

  select greatest(1, least(coalesce(participant_count, 6), 99))
    into target_count
  from public.dungeons
  where id = p_dungeon_id;

  if target_count is null then
    raise exception '副本不存在';
  end if;

  select mr.id
    into existing_room_id
  from public.match_room_players mrp
  join public.match_rooms mr on mr.id = mrp.room_id
  where mr.dungeon_id = p_dungeon_id
    and mr.room_status = 'running'
    and mrp.player_code_hash = p_player_code_hash
  order by mr.created_at desc
  limit 1;

  if existing_room_id is not null then
    return jsonb_build_object(
      'status', 'already_matched',
      'roomId', existing_room_id,
      'targetPlayerCount', target_count,
      'queuedCount', (
        select count(*)::integer
        from public.match_queue
        where dungeon_id = p_dungeon_id and status = 'queued'
      )
    );
  end if;

  insert into public.match_queue (dungeon_id, player_code_hash, player_name, status)
  values (p_dungeon_id, p_player_code_hash, clean_player_name, 'queued')
  on conflict (dungeon_id, player_code_hash) where status = 'queued'
  do update set
    player_name = excluded.player_name,
    updated_at = now();

  with candidates as (
    select id, player_code_hash, player_name
    from public.match_queue
    where dungeon_id = p_dungeon_id
      and status = 'queued'
    order by created_at, id
    limit target_count
    for update skip locked
  ),
  created_room as (
    insert into public.match_rooms (dungeon_id, target_player_count, room_status)
    select p_dungeon_id, target_count, 'running'
    where (select count(*) from candidates) >= target_count
    returning id
  ),
  updated_queue as (
    update public.match_queue mq
    set
      status = 'matched',
      room_id = (select id from created_room),
      updated_at = now()
    where mq.id in (select id from candidates)
      and exists (select 1 from created_room)
    returning mq.id
  ),
  inserted_players as (
    insert into public.match_room_players (room_id, dungeon_id, player_code_hash, player_name)
    select (select id from created_room), p_dungeon_id, c.player_code_hash, c.player_name
    from candidates c
    where exists (select 1 from created_room)
      and exists (select 1 from updated_queue)
    on conflict (room_id, player_code_hash) do nothing
    returning player_code_hash
  )
  select id into created_room_id from created_room;

  select count(*)::integer
    into queued_count
  from public.match_queue
  where dungeon_id = p_dungeon_id
    and status = 'queued';

  return jsonb_build_object(
    'status', case when created_room_id is null then 'queued' else 'matched' end,
    'roomId', created_room_id,
    'targetPlayerCount', target_count,
    'queuedCount', queued_count
  );
end;
$$;

create or replace function public.cancel_match_queue(
  p_dungeon_id uuid,
  p_player_code_hash text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  cancelled_id bigint;
begin
  update public.match_queue
  set status = 'cancelled', updated_at = now()
  where dungeon_id = p_dungeon_id
    and player_code_hash = p_player_code_hash
    and status = 'queued'
  returning id into cancelled_id;

  return jsonb_build_object(
    'cancelled', cancelled_id is not null,
    'queuedCount', (
      select count(*)::integer
      from public.match_queue
      where dungeon_id = p_dungeon_id and status = 'queued'
    )
  );
end;
$$;

alter table public.match_rooms enable row level security;
alter table public.match_queue enable row level security;
alter table public.match_room_players enable row level security;

grant usage on schema public to service_role;
grant select, insert, update, delete on public.match_rooms to service_role;
grant select, insert, update, delete on public.match_queue to service_role;
grant select, insert, update, delete on public.match_room_players to service_role;
grant execute on function public.join_match_queue(uuid, text, text) to service_role;
grant execute on function public.cancel_match_queue(uuid, text) to service_role;
