-- Trial muster sessions for WeChat Mini Program sharing and random draw.
-- Run after match_system_migration.sql.

create extension if not exists pgcrypto with schema extensions;

alter table public.dungeons
  add column if not exists is_one_shot boolean not null default false;

create table if not exists public.match_musters (
  id uuid primary key default gen_random_uuid(),
  dungeon_id uuid not null references public.dungeons(id) on delete cascade,
  creator_code_hash text not null check (char_length(creator_code_hash) = 64),
  creator_name text not null check (char_length(trim(creator_name)) between 1 and 40),
  target_player_count integer not null default 6 check (target_player_count >= 1 and target_player_count <= 99),
  status text not null default 'open' check (status in ('open', 'drawn', 'cancelled')),
  opens_at timestamptz not null default now(),
  closes_at timestamptz not null,
  room_id uuid references public.match_rooms(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  drawn_at timestamptz
);

create table if not exists public.match_muster_participants (
  id bigint generated by default as identity primary key,
  muster_id uuid not null references public.match_musters(id) on delete cascade,
  dungeon_id uuid not null references public.dungeons(id) on delete cascade,
  player_code_hash text not null check (char_length(player_code_hash) = 64),
  player_name text not null check (char_length(trim(player_name)) between 1 and 40),
  status text not null default 'joined' check (status in ('joined', 'selected', 'not_selected', 'cancelled')),
  joined_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  selected_at timestamptz,
  unique (muster_id, player_code_hash)
);

alter table public.match_rooms
  add column if not exists muster_id uuid references public.match_musters(id) on delete set null;

create index if not exists match_musters_dungeon_status_idx
  on public.match_musters(dungeon_id, status, created_at desc);

create index if not exists match_musters_closes_at_idx
  on public.match_musters(status, closes_at);

create index if not exists match_muster_participants_muster_status_idx
  on public.match_muster_participants(muster_id, status, joined_at, id);

create index if not exists match_muster_participants_player_idx
  on public.match_muster_participants(player_code_hash, joined_at desc);

create index if not exists match_rooms_muster_idx
  on public.match_rooms(muster_id);

create or replace function public.has_player_joined_one_shot_dungeon(
  p_dungeon_id uuid,
  p_player_code_hash text
)
returns boolean
language sql
stable
set search_path = public
as $$
  select exists (
    select 1
    from public.match_room_players
    where dungeon_id = p_dungeon_id
      and player_code_hash = p_player_code_hash
  ) or exists (
    select 1
    from public.clear_records
    where dungeon_id = p_dungeon_id
      and invite_code_hash = p_player_code_hash
  );
$$;

create or replace function public.start_match_muster(
  p_dungeon_id uuid,
  p_creator_code_hash text,
  p_creator_name text,
  p_duration_seconds integer default 60
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  target_count integer;
  one_shot boolean;
  clean_creator_name text;
  duration_seconds integer;
  new_muster_id uuid;
  close_time timestamptz;
begin
  if p_dungeon_id is null then
    raise exception '副本 ID 不正确';
  end if;

  if p_creator_code_hash is null or char_length(p_creator_code_hash) <> 64 then
    raise exception '发起者身份不正确';
  end if;

  clean_creator_name := nullif(trim(p_creator_name), '');
  if clean_creator_name is null then
    raise exception '发起者昵称不能为空';
  end if;

  select greatest(1, least(coalesce(participant_count, 6), 99)), coalesce(is_one_shot, false)
    into target_count, one_shot
  from public.dungeons
  where id = p_dungeon_id;

  if target_count is null then
    raise exception '副本不存在';
  end if;

  if one_shot and public.has_player_joined_one_shot_dungeon(p_dungeon_id, p_creator_code_hash) then
    raise exception '你已经参与过该一次副本，不能再次发起或报名';
  end if;

  duration_seconds := greatest(10, least(coalesce(p_duration_seconds, 60), 3600));
  close_time := now() + make_interval(secs => duration_seconds);

  insert into public.match_musters (
    dungeon_id,
    creator_code_hash,
    creator_name,
    target_player_count,
    status,
    closes_at
  )
  values (
    p_dungeon_id,
    p_creator_code_hash,
    clean_creator_name,
    target_count,
    'open',
    close_time
  )
  returning id into new_muster_id;

  insert into public.match_muster_participants (
    muster_id,
    dungeon_id,
    player_code_hash,
    player_name,
    status
  )
  values (
    new_muster_id,
    p_dungeon_id,
    p_creator_code_hash,
    clean_creator_name,
    'joined'
  );

  return jsonb_build_object(
    'status', 'open',
    'musterId', new_muster_id,
    'targetPlayerCount', target_count,
    'closesAt', close_time,
    'creatorJoined', true
  );
end;
$$;

create or replace function public.join_match_muster(
  p_muster_id uuid,
  p_player_code_hash text,
  p_player_name text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  target_count integer;
  joined_count integer;
  muster_status text;
  close_time timestamptz;
  target_dungeon_id uuid;
  one_shot boolean;
  clean_player_name text;
begin
  if p_muster_id is null then
    raise exception '召集 ID 不正确';
  end if;

  if p_player_code_hash is null or char_length(p_player_code_hash) <> 64 then
    raise exception '玩家身份不正确';
  end if;

  clean_player_name := nullif(trim(p_player_name), '');
  if clean_player_name is null then
    raise exception '玩家昵称不能为空';
  end if;

  select m.dungeon_id, m.status, m.closes_at, m.target_player_count, coalesce(d.is_one_shot, false)
    into target_dungeon_id, muster_status, close_time, target_count, one_shot
  from public.match_musters m
  join public.dungeons d on d.id = m.dungeon_id
  where m.id = p_muster_id
  for update of m;

  if target_dungeon_id is null then
    raise exception '召集不存在';
  end if;

  if muster_status <> 'open' then
    raise exception '召集已经结束';
  end if;

  if now() >= close_time then
    raise exception '报名已截止，等待抽选结果';
  end if;

  if one_shot and public.has_player_joined_one_shot_dungeon(target_dungeon_id, p_player_code_hash) then
    raise exception '你已经参与过该一次副本，不能再次报名';
  end if;

  insert into public.match_muster_participants (
    muster_id,
    dungeon_id,
    player_code_hash,
    player_name,
    status,
    joined_at,
    updated_at
  )
  values (
    p_muster_id,
    target_dungeon_id,
    p_player_code_hash,
    clean_player_name,
    'joined',
    now(),
    now()
  )
  on conflict (muster_id, player_code_hash)
  do update set
    player_name = excluded.player_name,
    status = 'joined',
    updated_at = now();

  select count(*)::integer
    into joined_count
  from public.match_muster_participants
  where muster_id = p_muster_id
    and status = 'joined';

  return jsonb_build_object(
    'status', 'joined',
    'musterId', p_muster_id,
    'targetPlayerCount', target_count,
    'joinedCount', joined_count
  );
end;
$$;

create or replace function public.cancel_match_muster_join(
  p_muster_id uuid,
  p_player_code_hash text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  joined_count integer;
  cancelled_id bigint;
  muster_status text;
  close_time timestamptz;
begin
  select status, closes_at
    into muster_status, close_time
  from public.match_musters
  where id = p_muster_id
  for update;

  if muster_status is null then
    raise exception '召集不存在';
  end if;

  if muster_status <> 'open' or now() >= close_time then
    raise exception '召集已经截止，不能取消报名';
  end if;

  update public.match_muster_participants
  set status = 'cancelled', updated_at = now()
  where muster_id = p_muster_id
    and player_code_hash = p_player_code_hash
    and status = 'joined'
  returning id into cancelled_id;

  select count(*)::integer
    into joined_count
  from public.match_muster_participants
  where muster_id = p_muster_id
    and status = 'joined';

  return jsonb_build_object(
    'cancelled', cancelled_id is not null,
    'musterId', p_muster_id,
    'joinedCount', joined_count
  );
end;
$$;

create or replace function public.draw_match_muster(
  p_muster_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  target_count integer;
  joined_count integer;
  selected_count integer;
  muster_status text;
  close_time timestamptz;
  target_dungeon_id uuid;
  created_room_id uuid;
begin
  select dungeon_id, status, closes_at, target_player_count, room_id
    into target_dungeon_id, muster_status, close_time, target_count, created_room_id
  from public.match_musters
  where id = p_muster_id
  for update;

  if target_dungeon_id is null then
    raise exception '召集不存在';
  end if;

  if muster_status = 'drawn' then
    return jsonb_build_object(
      'status', 'drawn',
      'musterId', p_muster_id,
      'roomId', created_room_id,
      'targetPlayerCount', target_count,
      'selectedCount', (
        select count(*)::integer
        from public.match_muster_participants
        where muster_id = p_muster_id and status = 'selected'
      )
    );
  end if;

  if muster_status <> 'open' then
    return jsonb_build_object('status', muster_status, 'musterId', p_muster_id);
  end if;

  if now() < close_time then
    raise exception '召集尚未截止';
  end if;

  select count(*)::integer
    into joined_count
  from public.match_muster_participants
  where muster_id = p_muster_id
    and status = 'joined';

  if joined_count <= 0 then
    update public.match_musters
    set status = 'cancelled', updated_at = now(), drawn_at = now()
    where id = p_muster_id;

    return jsonb_build_object(
      'status', 'cancelled',
      'musterId', p_muster_id,
      'targetPlayerCount', target_count,
      'selectedCount', 0
    );
  end if;

  insert into public.match_rooms (dungeon_id, target_player_count, room_status, muster_id)
  values (target_dungeon_id, target_count, 'running', p_muster_id)
  returning id into created_room_id;

  with candidates as (
    select id
    from public.match_muster_participants
    where muster_id = p_muster_id
      and status = 'joined'
    order by random(), joined_at, id
    limit target_count
    for update
  ),
  selected as (
    update public.match_muster_participants mp
    set status = 'selected', selected_at = now(), updated_at = now()
    where mp.id in (select id from candidates)
    returning mp.player_code_hash, mp.player_name
  ),
  not_selected as (
    update public.match_muster_participants mp
    set status = 'not_selected', updated_at = now()
    where mp.muster_id = p_muster_id
      and mp.status = 'joined'
      and mp.id not in (select id from candidates)
    returning mp.id
  ),
  inserted_players as (
    insert into public.match_room_players (room_id, dungeon_id, player_code_hash, player_name)
    select created_room_id, target_dungeon_id, selected.player_code_hash, selected.player_name
    from selected
    on conflict (room_id, player_code_hash) do nothing
    returning player_code_hash
  )
  select count(*)::integer into selected_count from selected;

  update public.match_musters
  set
    status = 'drawn',
    room_id = created_room_id,
    updated_at = now(),
    drawn_at = now()
  where id = p_muster_id;

  return jsonb_build_object(
    'status', 'drawn',
    'musterId', p_muster_id,
    'roomId', created_room_id,
    'targetPlayerCount', target_count,
    'joinedCount', joined_count,
    'selectedCount', selected_count
  );
end;
$$;

alter table public.match_musters enable row level security;
alter table public.match_muster_participants enable row level security;

grant usage on schema public to service_role;
grant select, insert, update, delete on public.match_musters to service_role;
grant select, insert, update, delete on public.match_muster_participants to service_role;
grant select, update on public.dungeons to service_role;
grant execute on function public.has_player_joined_one_shot_dungeon(uuid, text) to service_role;
grant execute on function public.start_match_muster(uuid, text, text, integer) to service_role;
grant execute on function public.join_match_muster(uuid, text, text) to service_role;
grant execute on function public.cancel_match_muster_join(uuid, text) to service_role;
grant execute on function public.draw_match_muster(uuid) to service_role;
