-- Profile title grant system.
-- Run after player_profiles_migration.sql.

begin;

create table if not exists public.profile_titles (
  id bigint generated by default as identity primary key,
  invite_code_hash text not null check (char_length(invite_code_hash) = 64),
  display_name text not null check (char_length(trim(display_name)) between 1 and 40),
  title_text text not null check (char_length(trim(title_text)) between 1 and 32),
  title_god text not null default '' check (char_length(trim(title_god)) <= 20),
  title_note text not null default '' check (char_length(trim(title_note)) <= 120),
  granted_by_type text not null default 'admin' check (granted_by_type in ('admin', 'god')),
  granted_by_hash text not null,
  granted_by_name text not null check (char_length(trim(granted_by_name)) between 1 and 40),
  granted_at timestamptz not null default now(),
  is_active boolean not null default true,
  revoked_at timestamptz,
  revoked_by_hash text,
  revoked_by_name text
);

create unique index if not exists profile_titles_one_active_idx
  on public.profile_titles(invite_code_hash)
  where is_active;

create index if not exists profile_titles_player_idx
  on public.profile_titles(invite_code_hash, granted_at desc);

create index if not exists profile_titles_display_name_idx
  on public.profile_titles(display_name, is_active);

create index if not exists profile_titles_granter_idx
  on public.profile_titles(granted_by_type, granted_by_hash, granted_at desc);

alter table public.profile_titles enable row level security;

grant usage on schema public to service_role;
grant select, insert, update, delete on public.profile_titles to service_role;

commit;
