-- Profile curse system.
-- Run after profile_titles_migration.sql.

begin;

create table if not exists public.profile_curses (
  id bigint generated by default as identity primary key,
  invite_code_hash text not null check (char_length(invite_code_hash) = 64),
  display_name text not null check (char_length(trim(display_name)) between 1 and 40),
  curse_text text not null default '背弃诅咒' check (char_length(trim(curse_text)) between 1 and 32),
  curse_god text not null default '' check (char_length(trim(curse_god)) <= 20),
  curse_note text not null default '' check (char_length(trim(curse_note)) <= 120),
  granted_by_type text not null default 'admin' check (granted_by_type in ('admin', 'god')),
  granted_by_hash text not null,
  granted_by_name text not null check (char_length(trim(granted_by_name)) between 1 and 40),
  granted_at timestamptz not null default now(),
  is_active boolean not null default true,
  revoked_at timestamptz,
  revoked_by_hash text,
  revoked_by_name text
);

create index if not exists profile_curses_player_idx
  on public.profile_curses(invite_code_hash, granted_at desc);

create index if not exists profile_curses_active_player_idx
  on public.profile_curses(invite_code_hash, is_active, granted_at desc);

create index if not exists profile_curses_display_name_idx
  on public.profile_curses(display_name, is_active);

create index if not exists profile_curses_granter_idx
  on public.profile_curses(granted_by_type, granted_by_hash, granted_at desc);

alter table public.profile_curses enable row level security;

grant usage on schema public to service_role;
grant select, insert, update, delete on public.profile_curses to service_role;

commit;
