-- Score settlement and reviewer role system.
-- Run after player_profiles_migration.sql / invite setup migrations.

begin;

alter table public.invite_codes
  drop constraint if exists invite_codes_role_check;
alter table public.invite_codes
  add constraint invite_codes_role_check
  check (role in ('player', 'author', 'reviewer', 'admin'));

alter table public.player_profiles
  drop constraint if exists player_profiles_role_check;
alter table public.player_profiles
  add constraint player_profiles_role_check
  check (role in ('player', 'author', 'reviewer', 'admin'));

create table if not exists public.score_settlements (
  id uuid primary key default gen_random_uuid(),
  dungeon_name text not null check (char_length(trim(dungeon_name)) between 1 and 80),
  source_type text not null check (source_type in ('batch', 'single')),
  operator_code_hash text not null,
  operator_name text not null,
  raw_text text not null default '',
  remark text not null default '',
  total_players integer not null default 0 check (total_players >= 0),
  total_ascension numeric(8, 1) not null default 0,
  total_audience numeric(8, 1) not null default 0,
  total_score numeric(8, 1) not null default 0,
  client_request_id text,
  is_revoked boolean not null default false,
  revoke_remark text,
  revoked_by_hash text,
  revoked_by_name text,
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.score_settlement_entries (
  id bigint generated by default as identity primary key,
  settlement_id uuid not null references public.score_settlements(id) on delete cascade,
  player_code_hash text not null,
  player_name text not null check (char_length(trim(player_name)) between 1 and 40),
  score_deng numeric(8, 1) not null check (score_deng >= -30 and score_deng <= 30),
  score_jin numeric(8, 1) not null check (score_jin >= 0 and score_jin <= 3),
  total_add numeric(8, 1) generated always as (score_deng + score_jin) stored,
  created_at timestamptz not null default now()
);

create table if not exists public.score_change_logs (
  id bigint generated by default as identity primary key,
  player_code_hash text not null,
  player_name text not null,
  change_deng numeric(8, 1) not null default 0,
  change_jin numeric(8, 1) not null default 0,
  source_type text not null check (source_type in ('batch', 'single', 'revoke')),
  settlement_id uuid references public.score_settlements(id) on delete set null,
  operator_code_hash text,
  operator_name text,
  revoke_remark text,
  created_at timestamptz not null default now()
);

create table if not exists public.score_messages (
  id bigint generated by default as identity primary key,
  player_code_hash text not null,
  player_name text not null,
  settlement_id uuid references public.score_settlements(id) on delete set null,
  msg_type text not null check (msg_type in ('batch', 'single', 'revoke', 'broadcast')),
  content text not null check (char_length(trim(content)) between 1 and 1000),
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists score_settlements_created_idx
  on public.score_settlements(created_at desc);
create index if not exists score_settlements_operator_idx
  on public.score_settlements(operator_code_hash, created_at desc);
create unique index if not exists score_settlements_client_request_uidx
  on public.score_settlements(operator_code_hash, client_request_id)
  where client_request_id is not null;
create index if not exists score_entries_settlement_idx
  on public.score_settlement_entries(settlement_id);
create index if not exists score_entries_player_idx
  on public.score_settlement_entries(player_code_hash, created_at desc);
create index if not exists score_logs_player_idx
  on public.score_change_logs(player_code_hash, created_at desc);
create index if not exists score_messages_player_idx
  on public.score_messages(player_code_hash, is_read, created_at desc);

alter table public.score_settlements enable row level security;
alter table public.score_settlement_entries enable row level security;
alter table public.score_change_logs enable row level security;
alter table public.score_messages enable row level security;

grant usage on schema public to service_role;
grant select, insert, update, delete on public.score_settlements to service_role;
grant select, insert, update, delete on public.score_settlement_entries to service_role;
grant select, insert, update, delete on public.score_change_logs to service_role;
grant select, insert, update, delete on public.score_messages to service_role;
grant select, insert, update, delete on public.player_profiles to service_role;
grant select, insert, update, delete on public.invite_codes to service_role;

commit;
