-- Roll back talents caused by the old trickery display bug.
--
-- Rule after the fix:
-- - If original_faith_god = '欺诈', the real faith pool is always Pool欺诈.
-- - A profession pool is allowed only when the currently stored profession is still a 欺诈 profession.
-- - Talents/logs/counters from other pools are considered bug output and can be removed.
--
-- Run section 1 first. Run section 2 only after the preview is correct.

-- 1) Preview wrong-pool records.
with trickery_profiles as (
  select
    invite_code_hash,
    display_name,
    faith_god,
    original_faith_god,
    profession,
    case profession
      when '杂技演员' then 'Pool战士'
      when '诡术大师' then 'Pool法师'
      when '小丑' then 'Pool牧师'
      when '驭兽师' then 'Pool猎人'
      when '受害者' then 'Pool刺客'
      when '魔术师' then 'Pool歌者'
      else null
    end as trickery_profession_pool
  from public.player_profiles
  where original_faith_god = '欺诈'
), allowed_pools as (
  select invite_code_hash, 'Pool欺诈' as pool_key from trickery_profiles
  union all
  select invite_code_hash, trickery_profession_pool
  from trickery_profiles
  where trickery_profession_pool is not null
)
select bucket, display_name, pool_key, rows, fragment_delta
from (
  select 'owned_talents' as bucket, p.display_name, o.pool_key, count(*) as rows, 0::numeric as fragment_delta
  from public.owned_talents o
  join trickery_profiles p on p.invite_code_hash = o.invite_code_hash
  where not exists (
    select 1 from allowed_pools a where a.invite_code_hash = o.invite_code_hash and a.pool_key = o.pool_key
  )
  group by p.display_name, o.pool_key
  union all
  select 'talent_overflow_choices', p.display_name, c.pool_key, count(*), 0::numeric
  from public.talent_overflow_choices c
  join trickery_profiles p on p.invite_code_hash = c.invite_code_hash
  where not exists (
    select 1 from allowed_pools a where a.invite_code_hash = c.invite_code_hash and a.pool_key = c.pool_key
  )
  group by p.display_name, c.pool_key
  union all
  select 'talent_draw_logs', p.display_name, l.pool_key, count(*), coalesce(sum(l.fragment_gain), 0)
  from public.talent_draw_logs l
  join trickery_profiles p on p.invite_code_hash = l.invite_code_hash
  where not exists (
    select 1 from allowed_pools a where a.invite_code_hash = l.invite_code_hash and a.pool_key = l.pool_key
  )
  group by p.display_name, l.pool_key
  union all
  select 'talent_exchange_logs', p.display_name, e.pool_key, count(*), coalesce(sum(e.cost_fragment), 0)
  from public.talent_exchange_logs e
  join trickery_profiles p on p.invite_code_hash = e.invite_code_hash
  where not exists (
    select 1 from allowed_pools a where a.invite_code_hash = e.invite_code_hash and a.pool_key = e.pool_key
  )
  group by p.display_name, e.pool_key
  union all
  select 'talent_pool_counters', p.display_name, c.pool_key, count(*), 0::numeric
  from public.talent_pool_counters c
  join trickery_profiles p on p.invite_code_hash = c.invite_code_hash
  where not exists (
    select 1 from allowed_pools a where a.invite_code_hash = c.invite_code_hash and a.pool_key = c.pool_key
  )
  group by p.display_name, c.pool_key
) audit
order by display_name, bucket, pool_key;

-- 2) Rollback transaction.
begin;

create table if not exists public.trickery_talent_pool_rollback_backup_20260717 (
  id bigint generated by default as identity primary key,
  table_name text not null,
  row_data jsonb not null,
  backed_up_at timestamptz not null default now()
);

-- Back up rows before deleting.
with trickery_profiles as (
  select invite_code_hash from public.player_profiles where original_faith_god = '欺诈'
), allowed_pools as (
  select invite_code_hash, 'Pool欺诈' as pool_key from trickery_profiles
  union all
  select p.invite_code_hash,
    case p.profession
      when '杂技演员' then 'Pool战士'
      when '诡术大师' then 'Pool法师'
      when '小丑' then 'Pool牧师'
      when '驭兽师' then 'Pool猎人'
      when '受害者' then 'Pool刺客'
      when '魔术师' then 'Pool歌者'
      else null
    end
  from public.player_profiles p
  where p.original_faith_god = '欺诈'
)
insert into public.trickery_talent_pool_rollback_backup_20260717 (table_name, row_data)
select 'owned_talents', to_jsonb(o)
from public.owned_talents o
join trickery_profiles p on p.invite_code_hash = o.invite_code_hash
where not exists (select 1 from allowed_pools a where a.invite_code_hash = o.invite_code_hash and a.pool_key = o.pool_key)
union all
select 'talent_overflow_choices', to_jsonb(c)
from public.talent_overflow_choices c
join trickery_profiles p on p.invite_code_hash = c.invite_code_hash
where not exists (select 1 from allowed_pools a where a.invite_code_hash = c.invite_code_hash and a.pool_key = c.pool_key)
union all
select 'talent_draw_logs', to_jsonb(l)
from public.talent_draw_logs l
join trickery_profiles p on p.invite_code_hash = l.invite_code_hash
where not exists (select 1 from allowed_pools a where a.invite_code_hash = l.invite_code_hash and a.pool_key = l.pool_key)
union all
select 'talent_exchange_logs', to_jsonb(e)
from public.talent_exchange_logs e
join trickery_profiles p on p.invite_code_hash = e.invite_code_hash
where not exists (select 1 from allowed_pools a where a.invite_code_hash = e.invite_code_hash and a.pool_key = e.pool_key)
union all
select 'talent_pool_counters', to_jsonb(c)
from public.talent_pool_counters c
join trickery_profiles p on p.invite_code_hash = c.invite_code_hash
where not exists (select 1 from allowed_pools a where a.invite_code_hash = c.invite_code_hash and a.pool_key = c.pool_key);

-- Fragment rollback:
-- wrong draws may have granted fragments, so subtract those;
-- wrong exchanges spent fragments, so refund those.
with trickery_profiles as (
  select invite_code_hash from public.player_profiles where original_faith_god = '欺诈'
), allowed_pools as (
  select invite_code_hash, 'Pool欺诈' as pool_key from trickery_profiles
  union all
  select p.invite_code_hash,
    case p.profession
      when '杂技演员' then 'Pool战士'
      when '诡术大师' then 'Pool法师'
      when '小丑' then 'Pool牧师'
      when '驭兽师' then 'Pool猎人'
      when '受害者' then 'Pool刺客'
      when '魔术师' then 'Pool歌者'
      else null
    end
  from public.player_profiles p
  where p.original_faith_god = '欺诈'
), wrong_draws as (
  select l.invite_code_hash, count(*) as draw_count, coalesce(sum(l.fragment_gain), 0) as remove_fragment
  from public.talent_draw_logs l
  join trickery_profiles p on p.invite_code_hash = l.invite_code_hash
  where not exists (select 1 from allowed_pools a where a.invite_code_hash = l.invite_code_hash and a.pool_key = l.pool_key)
  group by l.invite_code_hash
), wrong_exchanges as (
  select e.invite_code_hash, coalesce(sum(e.cost_fragment), 0) as refund_fragment
  from public.talent_exchange_logs e
  join trickery_profiles p on p.invite_code_hash = e.invite_code_hash
  where not exists (select 1 from allowed_pools a where a.invite_code_hash = e.invite_code_hash and a.pool_key = e.pool_key)
  group by e.invite_code_hash
), fragment_fix as (
  select
    coalesce(d.invite_code_hash, e.invite_code_hash) as invite_code_hash,
    coalesce(d.remove_fragment, 0) as remove_fragment,
    coalesce(e.refund_fragment, 0) as refund_fragment
  from wrong_draws d
  full join wrong_exchanges e on e.invite_code_hash = d.invite_code_hash
)
update public.user_fragments f
set fragment_total = greatest(0, f.fragment_total - fragment_fix.remove_fragment + fragment_fix.refund_fragment),
    updated_at = now()
from fragment_fix
where f.invite_code_hash = fragment_fix.invite_code_hash;

with trickery_profiles as (
  select invite_code_hash from public.player_profiles where original_faith_god = '欺诈'
), allowed_pools as (
  select invite_code_hash, 'Pool欺诈' as pool_key from trickery_profiles
  union all
  select p.invite_code_hash,
    case p.profession
      when '杂技演员' then 'Pool战士'
      when '诡术大师' then 'Pool法师'
      when '小丑' then 'Pool牧师'
      when '驭兽师' then 'Pool猎人'
      when '受害者' then 'Pool刺客'
      when '魔术师' then 'Pool歌者'
      else null
    end
  from public.player_profiles p
  where p.original_faith_god = '欺诈'
), wrong_draws as (
  select l.invite_code_hash, count(*) as draw_count
  from public.talent_draw_logs l
  join trickery_profiles p on p.invite_code_hash = l.invite_code_hash
  where not exists (select 1 from allowed_pools a where a.invite_code_hash = l.invite_code_hash and a.pool_key = l.pool_key)
  group by l.invite_code_hash
)
update public.talent_draw_state s
set spent_draws = greatest(0, s.spent_draws - wrong_draws.draw_count),
    updated_at = now()
from wrong_draws
where s.invite_code_hash = wrong_draws.invite_code_hash;

-- Delete wrong-pool rows.
with trickery_profiles as (
  select invite_code_hash from public.player_profiles where original_faith_god = '欺诈'
), allowed_pools as (
  select invite_code_hash, 'Pool欺诈' as pool_key from trickery_profiles
  union all
  select p.invite_code_hash,
    case p.profession
      when '杂技演员' then 'Pool战士'
      when '诡术大师' then 'Pool法师'
      when '小丑' then 'Pool牧师'
      when '驭兽师' then 'Pool猎人'
      when '受害者' then 'Pool刺客'
      when '魔术师' then 'Pool歌者'
      else null
    end
  from public.player_profiles p
  where p.original_faith_god = '欺诈'
)
delete from public.owned_talents o
using trickery_profiles p
where o.invite_code_hash = p.invite_code_hash
  and not exists (select 1 from allowed_pools a where a.invite_code_hash = o.invite_code_hash and a.pool_key = o.pool_key);

with trickery_profiles as (
  select invite_code_hash from public.player_profiles where original_faith_god = '欺诈'
), allowed_pools as (
  select invite_code_hash, 'Pool欺诈' as pool_key from trickery_profiles
  union all
  select p.invite_code_hash,
    case p.profession
      when '杂技演员' then 'Pool战士'
      when '诡术大师' then 'Pool法师'
      when '小丑' then 'Pool牧师'
      when '驭兽师' then 'Pool猎人'
      when '受害者' then 'Pool刺客'
      when '魔术师' then 'Pool歌者'
      else null
    end
  from public.player_profiles p
  where p.original_faith_god = '欺诈'
)
delete from public.talent_overflow_choices c
using trickery_profiles p
where c.invite_code_hash = p.invite_code_hash
  and not exists (select 1 from allowed_pools a where a.invite_code_hash = c.invite_code_hash and a.pool_key = c.pool_key);

with trickery_profiles as (
  select invite_code_hash from public.player_profiles where original_faith_god = '欺诈'
), allowed_pools as (
  select invite_code_hash, 'Pool欺诈' as pool_key from trickery_profiles
  union all
  select p.invite_code_hash,
    case p.profession
      when '杂技演员' then 'Pool战士'
      when '诡术大师' then 'Pool法师'
      when '小丑' then 'Pool牧师'
      when '驭兽师' then 'Pool猎人'
      when '受害者' then 'Pool刺客'
      when '魔术师' then 'Pool歌者'
      else null
    end
  from public.player_profiles p
  where p.original_faith_god = '欺诈'
)
delete from public.talent_draw_logs l
using trickery_profiles p
where l.invite_code_hash = p.invite_code_hash
  and not exists (select 1 from allowed_pools a where a.invite_code_hash = l.invite_code_hash and a.pool_key = l.pool_key);

with trickery_profiles as (
  select invite_code_hash from public.player_profiles where original_faith_god = '欺诈'
), allowed_pools as (
  select invite_code_hash, 'Pool欺诈' as pool_key from trickery_profiles
  union all
  select p.invite_code_hash,
    case p.profession
      when '杂技演员' then 'Pool战士'
      when '诡术大师' then 'Pool法师'
      when '小丑' then 'Pool牧师'
      when '驭兽师' then 'Pool猎人'
      when '受害者' then 'Pool刺客'
      when '魔术师' then 'Pool歌者'
      else null
    end
  from public.player_profiles p
  where p.original_faith_god = '欺诈'
)
delete from public.talent_exchange_logs e
using trickery_profiles p
where e.invite_code_hash = p.invite_code_hash
  and not exists (select 1 from allowed_pools a where a.invite_code_hash = e.invite_code_hash and a.pool_key = e.pool_key);

with trickery_profiles as (
  select invite_code_hash from public.player_profiles where original_faith_god = '欺诈'
), allowed_pools as (
  select invite_code_hash, 'Pool欺诈' as pool_key from trickery_profiles
  union all
  select p.invite_code_hash,
    case p.profession
      when '杂技演员' then 'Pool战士'
      when '诡术大师' then 'Pool法师'
      when '小丑' then 'Pool牧师'
      when '驭兽师' then 'Pool猎人'
      when '受害者' then 'Pool刺客'
      when '魔术师' then 'Pool歌者'
      else null
    end
  from public.player_profiles p
  where p.original_faith_god = '欺诈'
)
delete from public.talent_pool_counters c
using trickery_profiles p
where c.invite_code_hash = p.invite_code_hash
  and not exists (select 1 from allowed_pools a where a.invite_code_hash = c.invite_code_hash and a.pool_key = c.pool_key);

-- Restore real faith binding for trickery-origin profiles.
update public.player_profiles
set faith_god = '欺诈',
    faith_path = '虚无',
    updated_at = now()
where original_faith_god = '欺诈'
  and faith_god <> '欺诈';

commit;

-- 3) Verify. This should return zero rows after rollback.
with trickery_profiles as (
  select invite_code_hash, display_name, profession from public.player_profiles where original_faith_god = '欺诈'
), allowed_pools as (
  select invite_code_hash, 'Pool欺诈' as pool_key from trickery_profiles
  union all
  select p.invite_code_hash,
    case p.profession
      when '杂技演员' then 'Pool战士'
      when '诡术大师' then 'Pool法师'
      when '小丑' then 'Pool牧师'
      when '驭兽师' then 'Pool猎人'
      when '受害者' then 'Pool刺客'
      when '魔术师' then 'Pool歌者'
      else null
    end
  from trickery_profiles p
)
select p.display_name, o.pool_key, count(*) as wrong_owned_rows
from public.owned_talents o
join trickery_profiles p on p.invite_code_hash = o.invite_code_hash
where not exists (select 1 from allowed_pools a where a.invite_code_hash = o.invite_code_hash and a.pool_key = o.pool_key)
group by p.display_name, o.pool_key;
