-- Activity rewards for 2026-08-17.
-- Run this whole script from the top in Supabase SQL Editor.
--
-- Rewards:
-- 1. 羔羊: 15 talent draws and exclusive title 〖愚人〗
-- 2. 讲个小故事: 13 talent draws
-- 3. 槐柏: 10 talent draws
-- 4. 棺材板: 6 talent draws
--
-- Talent draws are stored as event draws so they count toward pity.
-- Accounts below 1500 ascension score receive basic B/C event draws.
-- Accounts at 1500+ ascension score receive advanced S/A/B/C event draws.
-- Idempotent: the activity_reward_grants ledger prevents repeated grants for
-- the same activity key and player if this script is run again.

begin;

alter table public.talent_draw_state
  add column if not exists basic_spent_draws integer not null default 0
    check (basic_spent_draws >= 0),
  add column if not exists advanced_spent_draws integer not null default 0
    check (advanced_spent_draws >= 0),
  add column if not exists event_basic_draws integer not null default 0
    check (event_basic_draws >= 0),
  add column if not exists event_advanced_draws integer not null default 0
    check (event_advanced_draws >= 0),
  add column if not exists event_basic_spent_draws integer not null default 0
    check (event_basic_spent_draws >= 0),
  add column if not exists event_advanced_spent_draws integer not null default 0
    check (event_advanced_spent_draws >= 0);

create table if not exists public.activity_reward_grants (
  id bigint generated by default as identity primary key,
  activity_key text not null check (char_length(trim(activity_key)) between 1 and 80),
  invite_code_hash text not null check (char_length(invite_code_hash) = 64),
  display_name text not null check (char_length(trim(display_name)) between 1 and 40),
  reward_basic_draws integer not null default 0 check (reward_basic_draws >= 0),
  reward_advanced_draws integer not null default 0 check (reward_advanced_draws >= 0),
  reward_title text not null default '' check (char_length(trim(reward_title)) <= 32),
  note text not null default '' check (char_length(trim(note)) <= 160),
  granted_at timestamptz not null default now(),
  unique (activity_key, invite_code_hash)
);

create index if not exists activity_reward_grants_player_idx
  on public.activity_reward_grants(invite_code_hash, granted_at desc);

grant usage on schema public to service_role;
grant select, insert, update on public.activity_reward_grants to service_role;

create table if not exists public.profile_titles (
  id bigint generated by default as identity primary key,
  invite_code_hash text not null check (char_length(invite_code_hash) = 64),
  display_name text not null check (char_length(trim(display_name)) between 1 and 40),
  title_text text not null check (char_length(trim(title_text)) between 1 and 32),
  title_god text not null default '' check (char_length(trim(title_god)) <= 20),
  title_note text not null default '' check (char_length(trim(title_note)) <= 120),
  granted_by_type text not null default 'admin' check (granted_by_type in ('admin', 'god')),
  granted_by_hash text not null,
  granted_by_name text not null check (char_length(trim(granted_by_name)) between 1 and 40),
  granted_at timestamptz not null default now(),
  is_active boolean not null default true,
  revoked_at timestamptz,
  revoked_by_hash text,
  revoked_by_name text
);

create index if not exists profile_titles_player_idx
  on public.profile_titles(invite_code_hash, granted_at desc);

create index if not exists profile_titles_active_player_idx
  on public.profile_titles(invite_code_hash, is_active, granted_at desc);

create index if not exists profile_titles_display_name_idx
  on public.profile_titles(display_name, is_active);

grant select, insert, update, delete on public.profile_titles to service_role;

do $$
declare
  missing_names text;
  duplicate_names text;
  granted_rows integer;
begin
  with rewards(activity_key, target_name, draw_count, reward_title, reward_note) as (
    values
      ('activity_20260817_rank_rewards', '羔羊', 15, '〖愚人〗', '2026-08-17 活动第一名奖励'),
      ('activity_20260817_rank_rewards', '讲个小故事', 13, '', '2026-08-17 活动第二名奖励'),
      ('activity_20260817_rank_rewards', '槐柏', 10, '', '2026-08-17 活动第三名奖励'),
      ('activity_20260817_rank_rewards', '棺材板', 6, '', '2026-08-17 活动第四名奖励')
  ),
  matches as (
    select
      r.target_name,
      i.code_hash
    from rewards r
    join public.invite_codes i
      on i.is_active = true
    left join public.player_profiles p
      on p.invite_code_hash = i.code_hash
    where trim(i.display_name) = r.target_name
       or trim(coalesce(p.display_name, '')) = r.target_name
  )
  select string_agg(r.target_name, ', ' order by r.target_name)
  into missing_names
  from rewards r
  left join matches m on m.target_name = r.target_name
  where m.code_hash is null;

  if missing_names is not null then
    raise exception 'Missing active invite/profile for reward target(s): %', missing_names;
  end if;

  with rewards(activity_key, target_name, draw_count, reward_title, reward_note) as (
    values
      ('activity_20260817_rank_rewards', '羔羊', 15, '〖愚人〗', '2026-08-17 活动第一名奖励'),
      ('activity_20260817_rank_rewards', '讲个小故事', 13, '', '2026-08-17 活动第二名奖励'),
      ('activity_20260817_rank_rewards', '槐柏', 10, '', '2026-08-17 活动第三名奖励'),
      ('activity_20260817_rank_rewards', '棺材板', 6, '', '2026-08-17 活动第四名奖励')
  ),
  matches as (
    select
      r.target_name,
      i.code_hash
    from rewards r
    join public.invite_codes i
      on i.is_active = true
    left join public.player_profiles p
      on p.invite_code_hash = i.code_hash
    where trim(i.display_name) = r.target_name
       or trim(coalesce(p.display_name, '')) = r.target_name
  ),
  duplicated as (
    select target_name, count(*) as match_count
    from matches
    group by target_name
    having count(*) <> 1
  )
  select string_agg(target_name || '=' || match_count, ', ' order by target_name)
  into duplicate_names
  from duplicated;

  if duplicate_names is not null then
    raise exception 'Ambiguous reward target(s), expected exactly one active account each: %', duplicate_names;
  end if;

  with rewards(activity_key, target_name, draw_count, reward_title, reward_note) as (
    values
      ('activity_20260817_rank_rewards', '羔羊', 15, '〖愚人〗', '2026-08-17 活动第一名奖励'),
      ('activity_20260817_rank_rewards', '讲个小故事', 13, '', '2026-08-17 活动第二名奖励'),
      ('activity_20260817_rank_rewards', '槐柏', 10, '', '2026-08-17 活动第三名奖励'),
      ('activity_20260817_rank_rewards', '棺材板', 6, '', '2026-08-17 活动第四名奖励')
  ),
  resolved as (
    select
      r.activity_key,
      r.target_name,
      r.draw_count,
      r.reward_title,
      r.reward_note,
      i.code_hash,
      coalesce(p.display_name, i.display_name) as current_display_name,
      coalesce(p.ascension_score, 1000) as ascension_score,
      coalesce(p.ascension_score, 1000) >= 1500 as advanced_tier
    from rewards r
    join public.invite_codes i
      on i.is_active = true
    left join public.player_profiles p
      on p.invite_code_hash = i.code_hash
    where trim(i.display_name) = r.target_name
       or trim(coalesce(p.display_name, '')) = r.target_name
  ),
  inserted_grants as (
    insert into public.activity_reward_grants (
      activity_key,
      invite_code_hash,
      display_name,
      reward_basic_draws,
      reward_advanced_draws,
      reward_title,
      note
    )
    select
      activity_key,
      code_hash,
      current_display_name,
      case when advanced_tier then 0 else draw_count end,
      case when advanced_tier then draw_count else 0 end,
      reward_title,
      reward_note
    from resolved
    on conflict (activity_key, invite_code_hash) do nothing
    returning invite_code_hash, display_name, reward_basic_draws, reward_advanced_draws, reward_title, note
  ),
  upsert_draw_state as (
    insert into public.talent_draw_state (
      invite_code_hash,
      spent_draws,
      basic_spent_draws,
      advanced_spent_draws,
      event_basic_draws,
      event_advanced_draws,
      event_basic_spent_draws,
      event_advanced_spent_draws,
      updated_at
    )
    select
      invite_code_hash,
      0,
      0,
      0,
      reward_basic_draws,
      reward_advanced_draws,
      0,
      0,
      now()
    from inserted_grants
    on conflict (invite_code_hash) do update
    set event_basic_draws = coalesce(public.talent_draw_state.event_basic_draws, 0) + excluded.event_basic_draws,
        event_advanced_draws = coalesce(public.talent_draw_state.event_advanced_draws, 0) + excluded.event_advanced_draws,
        updated_at = now()
    returning invite_code_hash
  ),
  inserted_titles as (
    insert into public.profile_titles (
      invite_code_hash,
      display_name,
      title_text,
      title_god,
      title_note,
      granted_by_type,
      granted_by_hash,
      granted_by_name
    )
    select
      invite_code_hash,
      display_name,
      reward_title,
      '',
      note,
      'admin',
      'activity_20260817_rank_rewards',
      '馆主后台'
    from inserted_grants g
    where trim(reward_title) <> ''
      and not exists (
        select 1
        from public.profile_titles t
        where t.invite_code_hash = g.invite_code_hash
          and t.title_text = g.reward_title
          and t.is_active = true
      )
    returning id
  )
  select count(*) into granted_rows
  from upsert_draw_state;

  raise notice 'New activity reward rows granted: %', granted_rows;
end $$;

commit;

-- Verification 1: resolved reward targets and their current draw grants.
with rewards(activity_key, target_name, draw_count, reward_title, reward_note) as (
  values
    ('activity_20260817_rank_rewards', '羔羊', 15, '〖愚人〗', '2026-08-17 活动第一名奖励'),
    ('activity_20260817_rank_rewards', '讲个小故事', 13, '', '2026-08-17 活动第二名奖励'),
    ('activity_20260817_rank_rewards', '槐柏', 10, '', '2026-08-17 活动第三名奖励'),
    ('activity_20260817_rank_rewards', '棺材板', 6, '', '2026-08-17 活动第四名奖励')
),
resolved as (
  select
    r.target_name,
    r.draw_count,
    r.reward_title,
    i.code_hash,
    i.display_name as invite_display_name,
    coalesce(p.display_name, i.display_name) as profile_display_name,
    coalesce(p.ascension_score, 1000) as ascension_score,
    coalesce(p.ascension_score, 1000) >= 1500 as advanced_tier
  from rewards r
  join public.invite_codes i
    on i.is_active = true
  left join public.player_profiles p
    on p.invite_code_hash = i.code_hash
  where trim(i.display_name) = r.target_name
     or trim(coalesce(p.display_name, '')) = r.target_name
)
select
  target_name,
  invite_display_name,
  profile_display_name,
  draw_count as expected_draws,
  case when advanced_tier then 'advanced S/A/B/C' else 'basic B/C' end as grant_tier,
  coalesce(ds.event_basic_draws, 0) as event_basic_draws,
  coalesce(ds.event_advanced_draws, 0) as event_advanced_draws,
  reward_title,
  coalesce(t.title_text, '') as active_title
from resolved r
left join public.talent_draw_state ds
  on ds.invite_code_hash = r.code_hash
left join public.profile_titles t
  on t.invite_code_hash = r.code_hash
 and t.title_text = r.reward_title
 and t.is_active = true
order by expected_draws desc;

-- Verification 2: idempotency ledger rows for this activity.
select
  display_name,
  reward_basic_draws,
  reward_advanced_draws,
  reward_title,
  note,
  granted_at
from public.activity_reward_grants
where activity_key = 'activity_20260817_rank_rewards'
order by granted_at, display_name;
