-- S-rank talent choice slot support.
-- Run before deploying the updated fog-dungeon-action Edge Function.

begin;

alter table public.owned_talents
  add column if not exists s_slot integer;

alter table public.owned_talents
  drop constraint if exists owned_talents_s_slot_check;
alter table public.owned_talents
  add constraint owned_talents_s_slot_check
  check (s_slot is null or s_slot = 1);

alter table public.owned_talents
  drop constraint if exists owned_talents_storage_equipment_split_check;
alter table public.owned_talents
  add constraint owned_talents_storage_equipment_split_check
  check (
    (case when storage_slot is null then 0 else 1 end)
    + (case when equipped_slot is null then 0 else 1 end)
    + (case when s_slot is null then 0 else 1 end)
    <= 1
  );

with first_s as (
  select id
  from (
    select
      id,
      row_number() over (partition by invite_code_hash order by acquired_at asc, id asc) as rn
    from public.owned_talents
    where rank = 'S'
      and s_slot is null
  ) ranked
  where rn = 1
)
update public.owned_talents owned
set s_slot = 1,
    storage_slot = null,
    equipped_slot = null
from first_s
where owned.id = first_s.id;

create unique index if not exists owned_talents_one_s_slot_per_user_idx
  on public.owned_talents(invite_code_hash, s_slot)
  where s_slot is not null;

create table if not exists public.talent_s_choices (
  id bigint generated by default as identity primary key,
  invite_code_hash text not null check (char_length(invite_code_hash) = 64),
  pool_key text not null,
  source_draw_log_id bigint,
  source_draw_type text not null default 'single' check (source_draw_type in ('single', 'ten')),
  is_guarantee boolean not null default false,
  status text not null default 'pending' check (status in ('pending', 'used')),
  selected_talent_id integer,
  selected_talent_name text,
  created_at timestamptz not null default now(),
  used_at timestamptz
);

create index if not exists talent_s_choices_user_status_idx
  on public.talent_s_choices(invite_code_hash, status, created_at desc);

create index if not exists talent_s_choices_pool_idx
  on public.talent_s_choices(pool_key, status);

alter table public.talent_s_choices enable row level security;

grant usage on schema public to service_role;
grant select, insert, update, delete on public.talent_s_choices to service_role;
grant select, insert, update, delete on public.owned_talents to service_role;

commit;

-- Verification 1: should return no duplicate S slots.
select invite_code_hash, count(*) as s_slot_count
from public.owned_talents
where s_slot is not null
group by invite_code_hash
having count(*) > 1;

-- Verification 2: should return no row occupying more than one slot type.
select id, invite_code_hash, talent_name, storage_slot, equipped_slot, s_slot
from public.owned_talents
where (case when storage_slot is null then 0 else 1 end)
    + (case when equipped_slot is null then 0 else 1 end)
    + (case when s_slot is null then 0 else 1 end) > 1;
