-- Battle room player status hotfix.
-- Adds dungeon estimated duration display data and DM-managed battle statuses.

begin;

alter table public.dungeons
  add column if not exists estimated_duration text not null default '';

create table if not exists public.battle_room_player_statuses (
  id bigint generated by default as identity primary key,
  battle_room_id uuid not null references public.battle_rooms(id) on delete cascade,
  battle_room_player_id bigint not null references public.battle_room_players(id) on delete cascade,
  status_name text not null check (char_length(trim(status_name)) between 1 and 40),
  stack_count integer not null default 0 check (stack_count >= 0 and stack_count <= 999),
  is_public boolean not null default true,
  created_by_hash text not null default '',
  created_by_name text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists battle_room_player_statuses_room_player_idx
  on public.battle_room_player_statuses(battle_room_id, battle_room_player_id, created_at, id);

create index if not exists battle_room_player_statuses_public_idx
  on public.battle_room_player_statuses(battle_room_id, is_public);

alter table public.battle_room_player_statuses enable row level security;

grant usage on schema public to service_role;
grant select, insert, update, delete on public.battle_room_player_statuses to service_role;

commit;

-- Verification.
select table_name, column_name
from information_schema.columns
where table_schema = 'public'
  and (
    (table_name = 'dungeons' and column_name = 'estimated_duration')
    or table_name = 'battle_room_player_statuses'
  )
order by table_name, ordinal_position;
