-- Mini Program battle room V1.
-- Run after battle_room_system_20260810.sql.
-- This snapshot is battle-local: cooldown changes never write back to owned_talents.

begin;

alter table public.battle_room_players
  add column if not exists team_name text not null default 'A',
  add column if not exists attack_value integer not null default 1 check (attack_value >= 0 and attack_value <= 9999),
  add column if not exists abilities jsonb not null default '[]'::jsonb;

create table if not exists public.battle_room_actions (
  id bigint generated by default as identity primary key,
  battle_room_id uuid not null references public.battle_rooms(id) on delete cascade,
  battle_room_player_id bigint not null references public.battle_room_players(id) on delete cascade,
  actor_code_hash text not null check (char_length(actor_code_hash) = 64),
  actor_name text not null check (char_length(trim(actor_name)) between 1 and 40),
  round_no integer not null check (round_no >= 1 and round_no <= 999),
  action_text text not null check (char_length(trim(action_text)) between 1 and 1200),
  action_status text not null default 'submitted' check (action_status in ('submitted', 'resolved', 'dismissed')),
  ability_key text not null default '',
  cooldown_until_round integer,
  dm_note text not null default '',
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create index if not exists battle_room_actions_room_round_idx
  on public.battle_room_actions(battle_room_id, round_no, created_at desc, id desc);

create index if not exists battle_room_actions_player_idx
  on public.battle_room_actions(battle_room_player_id, created_at desc, id desc);

alter table public.battle_room_actions enable row level security;

grant usage on schema public to service_role;
grant select, insert, update, delete on public.battle_room_actions to service_role;

commit;

-- Verification.
select table_name, column_name
from information_schema.columns
where table_schema = 'public'
  and ((table_name = 'battle_room_players' and column_name in ('team_name', 'attack_value', 'abilities'))
    or table_name = 'battle_room_actions')
order by table_name, ordinal_position;
