-- Website battle room system.
-- Run after match_system_migration.sql / match_muster_migration.sql.
-- This script only creates the battle-room tables used by fog-dungeon-action.

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.battle_rooms (
  id uuid primary key default gen_random_uuid(),
  source_match_room_id uuid unique references public.match_rooms(id) on delete set null,
  dungeon_id uuid not null references public.dungeons(id) on delete cascade,
  host_code_hash text not null check (char_length(host_code_hash) = 64),
  host_name text not null check (char_length(trim(host_name)) between 1 and 40),
  room_status text not null default 'active' check (room_status in ('active', 'finished', 'cancelled')),
  current_round integer not null default 1 check (current_round >= 1 and current_round <= 999),
  note text not null default '',
  expires_at timestamptz not null default (now() + interval '6 hours'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  finished_at timestamptz
);

create table if not exists public.battle_room_players (
  id bigint generated by default as identity primary key,
  battle_room_id uuid not null references public.battle_rooms(id) on delete cascade,
  player_code_hash text not null check (char_length(player_code_hash) = 64),
  player_name text not null check (char_length(trim(player_name)) between 1 and 40),
  faith_god text not null default '',
  profession text not null default '',
  class_name text not null default '',
  ascension_score numeric not null default 1000,
  max_hp integer not null default 80 check (max_hp >= 1 and max_hp <= 9999),
  current_hp integer not null default 80 check (current_hp >= 0 and current_hp <= 9999),
  shield integer not null default 0 check (shield >= 0 and shield <= 9999),
  is_defeated boolean not null default false,
  seat_order integer not null default 1,
  note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.battle_room_logs (
  id bigint generated by default as identity primary key,
  battle_room_id uuid not null references public.battle_rooms(id) on delete cascade,
  actor_code_hash text not null check (char_length(actor_code_hash) = 64),
  actor_name text not null check (char_length(trim(actor_name)) between 1 and 40),
  action_type text not null check (action_type in ('create', 'round', 'damage', 'heal', 'shield', 'set_hp', 'revive', 'defeat', 'note', 'finish', 'cancel', 'cooldown')),
  target_player_id bigint references public.battle_room_players(id) on delete set null,
  target_player_name text not null default '',
  amount integer,
  note text not null default '',
  round_no integer not null default 1,
  created_at timestamptz not null default now()
);

create unique index if not exists battle_room_players_one_per_room_idx
  on public.battle_room_players(battle_room_id, player_code_hash);

create index if not exists battle_rooms_source_match_room_idx
  on public.battle_rooms(source_match_room_id);

create index if not exists battle_rooms_dungeon_status_idx
  on public.battle_rooms(dungeon_id, room_status, created_at desc);

create index if not exists battle_room_players_hash_idx
  on public.battle_room_players(player_code_hash, updated_at desc);

create index if not exists battle_room_logs_room_idx
  on public.battle_room_logs(battle_room_id, created_at desc, id desc);

alter table public.battle_rooms enable row level security;
alter table public.battle_room_players enable row level security;
alter table public.battle_room_logs enable row level security;

grant usage on schema public to service_role;
grant select, insert, update, delete on public.battle_rooms to service_role;
grant select, insert, update, delete on public.battle_room_players to service_role;
grant select, insert, update, delete on public.battle_room_logs to service_role;
