-- Independent exclusive talent slot and reusable template support.
-- Run once in Supabase SQL Editor before deploying the matching Edge Function.

begin;

create table if not exists public.exclusive_talent_slots (
  invite_code_hash text primary key check (char_length(invite_code_hash) = 64),
  manual_enabled boolean not null default false,
  enabled_note text not null default '',
  enabled_by_hash text,
  enabled_by_name text,
  enabled_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.exclusive_talents (
  invite_code_hash text primary key check (char_length(invite_code_hash) = 64),
  talent_name text not null default '',
  rank text not null default 'EX' check (rank = 'EX'),
  effect text not null default '',
  cooldown text not null default '',
  action_cost integer not null default 0 check (action_cost >= 0),
  admin_note text not null default '',
  is_enabled boolean not null default true,
  created_by_hash text,
  created_by_name text,
  updated_by_hash text,
  updated_by_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.exclusive_talent_templates (
  id bigint generated by default as identity primary key,
  template_name text not null,
  talent_name text not null default '',
  rank text not null default 'EX' check (rank = 'EX'),
  effect text not null default '',
  cooldown text not null default '',
  action_cost integer not null default 0 check (action_cost >= 0),
  admin_note text not null default '',
  is_enabled boolean not null default true,
  created_by_hash text,
  created_by_name text,
  updated_by_hash text,
  updated_by_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists exclusive_talent_slots_manual_enabled_idx
  on public.exclusive_talent_slots(manual_enabled, updated_at desc);
create index if not exists exclusive_talent_templates_enabled_idx
  on public.exclusive_talent_templates(is_enabled, updated_at desc);

alter table public.exclusive_talent_slots enable row level security;
alter table public.exclusive_talents enable row level security;
alter table public.exclusive_talent_templates enable row level security;

grant select, insert, update, delete on public.exclusive_talent_slots to service_role;
grant select, insert, update, delete on public.exclusive_talents to service_role;
grant select, insert, update, delete on public.exclusive_talent_templates to service_role;
grant usage, select on sequence public.exclusive_talent_templates_id_seq to service_role;

commit;

select
  'exclusive_talent_tables' as item,
  count(*) as tables_found
from information_schema.tables
where table_schema = 'public'
  and table_name in ('exclusive_talent_slots', 'exclusive_talents', 'exclusive_talent_templates');
