-- Promo code redemption for the 2026-08-11 memorial gift.
-- Run this whole script from the top in Supabase SQL Editor.
-- Today's code: 灵魂安眠，生命终焉
-- Reward: ascension score +20, basic talent draws +5.

begin;

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.talent_draw_state (
  invite_code_hash text primary key check (char_length(invite_code_hash) = 64),
  spent_draws integer not null default 0 check (spent_draws >= 0),
  basic_spent_draws integer not null default 0 check (basic_spent_draws >= 0),
  advanced_spent_draws integer not null default 0 check (advanced_spent_draws >= 0),
  event_basic_draws integer not null default 0 check (event_basic_draws >= 0),
  event_advanced_draws integer not null default 0 check (event_advanced_draws >= 0),
  updated_at timestamptz not null default now()
);

alter table public.talent_draw_state
  add column if not exists basic_spent_draws integer not null default 0 check (basic_spent_draws >= 0),
  add column if not exists advanced_spent_draws integer not null default 0 check (advanced_spent_draws >= 0),
  add column if not exists event_basic_draws integer not null default 0 check (event_basic_draws >= 0),
  add column if not exists event_advanced_draws integer not null default 0 check (event_advanced_draws >= 0);

create table if not exists public.promo_codes (
  id uuid primary key default gen_random_uuid(),
  code_text text not null unique check (char_length(trim(code_text)) between 1 and 120),
  reward_ascension_score numeric(8, 1) not null default 0 check (reward_ascension_score >= 0),
  reward_basic_draws integer not null default 0 check (reward_basic_draws >= 0),
  reward_advanced_draws integer not null default 0 check (reward_advanced_draws >= 0),
  starts_at timestamptz not null default now(),
  expires_at timestamptz not null,
  is_active boolean not null default true,
  note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.promo_code_redemptions (
  id bigint generated by default as identity primary key,
  promo_code_id uuid not null references public.promo_codes(id) on delete cascade,
  invite_code_hash text not null check (char_length(invite_code_hash) = 64),
  display_name text not null default '',
  reward_ascension_score numeric(8, 1) not null default 0 check (reward_ascension_score >= 0),
  reward_basic_draws integer not null default 0 check (reward_basic_draws >= 0),
  reward_advanced_draws integer not null default 0 check (reward_advanced_draws >= 0),
  redeemed_at timestamptz not null default now(),
  unique (promo_code_id, invite_code_hash)
);

create index if not exists promo_codes_active_expires_idx
  on public.promo_codes(is_active, expires_at desc);

create index if not exists promo_redemptions_invite_idx
  on public.promo_code_redemptions(invite_code_hash, redeemed_at desc);

alter table public.promo_codes enable row level security;
alter table public.promo_code_redemptions enable row level security;

revoke all on public.promo_codes from anon, authenticated;
revoke all on public.promo_code_redemptions from anon, authenticated;
grant select, insert, update, delete on public.promo_codes to service_role;
grant select, insert, update, delete on public.promo_code_redemptions to service_role;

create or replace function public.redeem_promo_code(
  p_code_text text,
  p_invite_code_hash text
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $redeem$
declare
  v_code_text text := btrim(coalesce(p_code_text, ''));
  v_code public.promo_codes%rowtype;
  v_profile record;
  v_redemption_id bigint;
  v_next_ascension numeric(8, 1);
begin
  if char_length(coalesce(p_invite_code_hash, '')) <> 64 then
    return jsonb_build_object('ok', false, 'error', '登录身份无效，请重新输入入局谕令');
  end if;

  if v_code_text = '' then
    return jsonb_build_object('ok', false, 'error', '请输入兑换口令');
  end if;

  select *
  into v_code
  from public.promo_codes
  where code_text = v_code_text
  for update;

  if not found then
    return jsonb_build_object('ok', false, 'error', '兑换口令不存在');
  end if;

  if v_code.is_active is not true then
    return jsonb_build_object('ok', false, 'error', '兑换口令已关闭');
  end if;

  if now() < v_code.starts_at then
    return jsonb_build_object('ok', false, 'error', '兑换口令尚未开放');
  end if;

  if now() > v_code.expires_at then
    return jsonb_build_object('ok', false, 'error', '兑换口令已过期');
  end if;

  select invite_code_hash, display_name, role, ascension_score
  into v_profile
  from public.player_profiles
  where invite_code_hash = p_invite_code_hash
  for update;

  if not found then
    return jsonb_build_object('ok', false, 'error', '请先保存个人档案，再兑换口令');
  end if;

  if v_profile.role not in ('player', 'author', 'reviewer', 'admin') then
    return jsonb_build_object('ok', false, 'error', '特殊账号不参与兑换');
  end if;

  insert into public.promo_code_redemptions (
    promo_code_id,
    invite_code_hash,
    display_name,
    reward_ascension_score,
    reward_basic_draws,
    reward_advanced_draws
  )
  values (
    v_code.id,
    p_invite_code_hash,
    v_profile.display_name,
    v_code.reward_ascension_score,
    v_code.reward_basic_draws,
    v_code.reward_advanced_draws
  )
  on conflict (promo_code_id, invite_code_hash) do nothing
  returning id into v_redemption_id;

  if v_redemption_id is null then
    return jsonb_build_object('ok', false, 'error', '这个口令已经兑换过了');
  end if;

  v_next_ascension := least(
    999999::numeric,
    round((coalesce(v_profile.ascension_score, 1000) + v_code.reward_ascension_score)::numeric, 1)
  )::numeric(8, 1);

  update public.player_profiles
  set ascension_score = v_next_ascension,
      updated_at = now()
  where invite_code_hash = p_invite_code_hash;

  insert into public.talent_draw_state (
    invite_code_hash,
    spent_draws,
    basic_spent_draws,
    advanced_spent_draws,
    event_basic_draws,
    event_advanced_draws,
    updated_at
  )
  values (
    p_invite_code_hash,
    0,
    0,
    0,
    v_code.reward_basic_draws,
    v_code.reward_advanced_draws,
    now()
  )
  on conflict (invite_code_hash) do update
  set event_basic_draws = public.talent_draw_state.event_basic_draws + excluded.event_basic_draws,
      event_advanced_draws = public.talent_draw_state.event_advanced_draws + excluded.event_advanced_draws,
      updated_at = now();

  return jsonb_build_object(
    'ok', true,
    'promo_code', v_code.code_text,
    'display_name', v_profile.display_name,
    'reward_ascension_score', v_code.reward_ascension_score,
    'reward_basic_draws', v_code.reward_basic_draws,
    'reward_advanced_draws', v_code.reward_advanced_draws,
    'new_ascension_score', v_next_ascension,
    'redeemed_at', now()
  );
end
$redeem$;

revoke all on function public.redeem_promo_code(text, text) from public;
grant execute on function public.redeem_promo_code(text, text) to service_role;

insert into public.promo_codes (
  code_text,
  reward_ascension_score,
  reward_basic_draws,
  reward_advanced_draws,
  starts_at,
  expires_at,
  is_active,
  note
)
values (
  '灵魂安眠，生命终焉',
  20,
  5,
  0,
  timestamptz '2026-08-11 00:00:00+08',
  timestamptz '2026-08-11 23:59:59+08',
  true,
  '2026-08-11 今日限时兑换：登神分 20，基础抽数 5'
)
on conflict (code_text) do update
set reward_ascension_score = excluded.reward_ascension_score,
    reward_basic_draws = excluded.reward_basic_draws,
    reward_advanced_draws = excluded.reward_advanced_draws,
    starts_at = excluded.starts_at,
    expires_at = excluded.expires_at,
    is_active = true,
    note = excluded.note,
    updated_at = now();

commit;

select
  code_text,
  reward_ascension_score,
  reward_basic_draws,
  reward_advanced_draws,
  starts_at,
  expires_at,
  is_active,
  note
from public.promo_codes
where code_text = '灵魂安眠，生命终焉';
