-- Talent inventory and equipped-slot system.
-- Run after talent_pool_migration.sql.

begin;

alter table public.owned_talents
  add column if not exists storage_slot integer,
  add column if not exists equipped_slot integer;

alter table public.owned_talents
  drop constraint if exists owned_talents_storage_slot_check;
alter table public.owned_talents
  add constraint owned_talents_storage_slot_check
  check (storage_slot is null or (storage_slot between 1 and 8));

alter table public.owned_talents
  drop constraint if exists owned_talents_equipped_slot_check;
alter table public.owned_talents
  add constraint owned_talents_equipped_slot_check
  check (equipped_slot is null or (equipped_slot between 1 and 3));

create table if not exists public.talent_overflow_choices (
  id bigint generated by default as identity primary key,
  invite_code_hash text not null check (char_length(invite_code_hash) = 64),
  pool_key text not null,
  talent_id integer not null,
  talent_name text not null,
  rank text not null check (rank in ('B', 'C')),
  source text not null default 'draw' check (source in ('draw', 'exchange', 'migration')),
  created_at timestamptz not null default now()
);

with ranked as (
  select
    id,
    invite_code_hash,
    pool_key,
    talent_id,
    talent_name,
    rank,
    row_number() over (partition by invite_code_hash order by acquired_at asc, id asc) as rn
  from public.owned_talents
)
update public.owned_talents owned
set storage_slot = ranked.rn
from ranked
where owned.id = ranked.id
  and ranked.rn <= 8
  and owned.storage_slot is null;

with overflow as (
  select
    id,
    invite_code_hash,
    pool_key,
    talent_id,
    talent_name,
    rank
  from (
    select
      id,
      invite_code_hash,
      pool_key,
      talent_id,
      talent_name,
      rank,
      row_number() over (partition by invite_code_hash order by acquired_at asc, id asc) as rn
    from public.owned_talents
  ) ranked
  where rn > 8
)
insert into public.talent_overflow_choices (invite_code_hash, pool_key, talent_id, talent_name, rank, source)
select invite_code_hash, pool_key, talent_id, talent_name, rank, 'migration'
from overflow;

delete from public.owned_talents owned
using (
  select id
  from (
    select
      id,
      row_number() over (partition by invite_code_hash order by acquired_at asc, id asc) as rn
    from public.owned_talents
  ) ranked
  where rn > 8
) overflow
where owned.id = overflow.id;

create unique index if not exists owned_talents_one_storage_slot_per_user_idx
  on public.owned_talents(invite_code_hash, storage_slot)
  where storage_slot is not null;

create unique index if not exists owned_talents_one_equipped_slot_per_user_idx
  on public.owned_talents(invite_code_hash, equipped_slot)
  where equipped_slot is not null;

create index if not exists talent_overflow_choices_user_idx
  on public.talent_overflow_choices(invite_code_hash, created_at desc);

alter table public.talent_overflow_choices enable row level security;

grant usage on schema public to service_role;
grant select, insert, update, delete on public.talent_overflow_choices to service_role;
grant select, insert, update, delete on public.owned_talents to service_role;

commit;
